### ISSUE TITLE
Add lib to scala-steward

### ISSUE THREAD

**Issue by gabfssilva** [matsluni/aws-spi-akka-http#2]
it'll help to keep the AWS SDK version up to date: https://github.com/fthomas/scala-steward

**Comment by matsluni** [comment]
I also thought about using it.

Also, the changes in the aws sdk are normally not changes in the SPI for the async http provider, that’s why I was reluctant to add anything like this.

I also thought about to change the use of `http-client-spi` to `provided` to better handle maybe version conflicts better. I am not sure yet. 

What do you think about to wait and see a bit to get some experience how this behaves?

**Comment by gabfssilva** [comment]
I think we can do both: change to `provided` and also keep it up to date using scala-steward. I'm afraid of big version bumps and not seeing a big change that could arrive with it.

**Comment by matsluni** [comment]
The support for scala steward was added with 8fc65c0 and scala-steward-org/repos@67a696454f6759fd13a11a18907fa98c1144af38. Will close this for now.
