### ISSUE TITLE
sdkclientexception "Unable to execute HTTP request: Service returned null 'Content-Length'."

### ISSUE THREAD

**Issue by alexmnyc** [matsluni/aws-spi-akka-http#42]
getting this

sdkclientexception "Unable to execute HTTP request: Service returned null 'Content-Length'."

**Comment by matsluni** [comment]
@alexmnyc Thanks for forwarding the error message. 
Can you provide more details, a reproducer or for which aws service this happens. 
With the limited information you provided, I can't help you unfortunately.

**Comment by AdrianMF** [comment]
I just received this as well when trying to download a file from an S3 bucket

**Comment by matsluni** [comment]
I found this in the aws client code: 
https://github.com/aws/aws-sdk-java-v2/blob/cdfb7d3f6a7dafb37be84f6e95e49feb0d0af273/services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/handlers/EnableTrailingChecksumInterceptor.java#L65

**Comment by kyle-st** [comment]
I believe I may be experiencing a similar issue. Trying to stream an image file to S3, which the default client requires "Content-Length" to be set as it cannot be inferred. However, the response I get back from S3 has an error message `The request signature we calculated does not match the signature you provided. Check your key and signing method.` and the following entry for CanonicalRequest:
```xml
<CanonicalRequest>PUT
    REDACTED

    ...
    amz-sdk-retry:0/0/500
    content-disposition:inline
    content-length:
    content-type:image/jpeg
    host: REDACTED
    x-amz-content-sha256:UNSIGNED-PAYLOAD
    x-amz-date:20200610T002249Z

    amz-sdk-invocation-id;amz-sdk-retry;content-disposition;content-length;content-type;host;x-amz-content-sha256;x-amz-date
    UNSIGNED-PAYLOAD</CanonicalRequest>
```

**Comment by vigoo** [comment]
The `PUT` case seems to work if the `Expect: 100-continue` header is omitted from the request. I'm not sure though what exactly this mean (and an interesting fact that the same happens with a similar service provider I wrote for http4s)

**Comment by matsluni** [comment]
Thanks @vigoo for linking the issues and proposing a possible fix.

**Comment by IIVat** [comment]
Today I have encountered with the issue as well. The problem is here:
`    val result = Http()
      .singleRequest(httpRequest, settings = connectionPoolSettings)
      .flatMap { response =>
        val sdkResponse = SdkHttpFullResponse.builder()
          .headers(response.headers.groupBy(_.name()).map{ case (k, v) => k -> v.map(_.value()).asJava }.asJava)
          .statusCode(response.status.intValue())
          .statusText(response.status.reason)
          .build` 

Headers are mapped from response, but `cotent-length` is not there. It is in HttpEntity. So solution is simple. To take `cotent-length` from HttpEntity and put it in headers.
