### ISSUE TITLE
Caused by: java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 2

### ISSUE THREAD

**Issue by gabfssilva** [matsluni/aws-spi-akka-http#5]
I think this was solved with the last PR, but, I'm getting this error when I try to create a queue using the 0.0.4. Is there anything left before releasing 0.5 (also for 2.13.RC1)?

**Comment by matsluni** [comment]
Just pushed the artifacts for 0.0.5 to sonatype. They should soon be available on maven central.
